name: frontend:publish_gh_pages

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish gh pages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [ '16' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install packages
        run: npm ci
      - name: Run build
        run: npm run build
      - name: Publish generated content to gh pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
