name: frontend:lint

on: [ push ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [ '18' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install packages
        run: yarn install --inline-builds
      - name: Run linter
        run: yarn lint
